---
parser: "babel-eslint"
env:
  browser: true
plugins: ["import", "react", "react-hooks"]
extends: ["airbnb", "plugin:react/recommended", "prettier"]
settings:
  import/resolver:
    node: {}
    webpack:
      config: webpack.config.js
  react:
    version: detect
rules:
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/label-has-associated-control: 0
  jsx-a11y/control-has-associated-label: 0
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "warn"
