web:
  image: skyportal/web
  ports:
    - "9000:5000"
    - "9001:5001"
  links:
    - db

db:
  build: postgres:9.6-q3c
  environment:
    - POSTGRES_USER=skyportal
    - POSTGRES_PASSWORD=
    - POSTGRES_DB=skyportal
