version: "3.3"

services:
  web:
    image: skyportal/web
    ports:
      - "9000:5000"
      - "9001:5001"
    links:
      - db

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=skyportal
      - POSTGRES_PASSWORD=latropyks
      - POSTGRES_DB=skyportal
