database:
  database: skyportal_test
  user: skyportal
  host: localhost
  port: 5432
  password:

server:
  auth:
    debug_login: True
    google_oauth2_key:
    google_oauth2_secret:
  log:
    api_calls: True
