apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "skyportal.fullname" . }}-config
  labels:
    app: {{ template "skyportal.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}