drop_tables: true
create_tables: true
print_tables: true
create_permissions: true
users:
  - username: testadmin@cesium-ml.org
    role_ids:
      - Super admin
    tokens:
      - name: "load_demo_data token"
        print: true
        permissions:
          - "Manage groups"
          - "Manage sources"
          - "Upload data"
          - "Comment"
          - "Post taxonomy"
          - "Manage users"
          - "System admin"
  - username: groupadmin@cesium-ml.org
    role_ids:
      - Group admin
  - username: fulluser@cesium-ml.org
    role_ids:
      - Full user
  - username: viewonlyuser@cesium-ml.org
    role_ids:
      - View only
groups:
  - name: Program A
    group_admins:
      - testadmin@cesium-ml.org
      - groupadmin@cesium-ml.org
    token: "load_demo_data token"
    members:
      - username: viewonlyuser@cesium-ml.org
        admin: false
      - username: fulluser@cesium-ml.org
        admin: false
    filters:
      - query_string: "sample_query_string"
        name: "example filter"
  - name: Program B
    group_admins:
      - testadmin@cesium-ml.org
      - groupadmin@cesium-ml.org
    token: "load_demo_data token"
telescopes:
  - name: Palomar 1.5m
    nickname: P60
    lat: 33.3633675
    lon: -116.8361345
    elevation: 1870
    diameter: 1.5
    skycam: http://bianca.palomar.caltech.edu/images/allsky/AllSkyCurrentImage.JPG
    robotic: true
    group_names:
      - Program A
    token: "load_demo_data token"
  - name: Nordic Optical Telescope
    nickname: NOT
    lat: 28.75
    lon: 17.88
    elevation: 2000
    diameter: 2.56
    skycam: http://catserver.ing.iac.es/weather/archive/concam/concam_labels.png
    robotic: true
    group_names:
      - Program A
    token: "load_demo_data token"
  - diameter: 10.0
    elevation: 4160.0
    lat: 19.8283
    lon: -155.478
    name: Keck II 10m
    id: Keck2
    skycam: https://www2.keck.hawaii.edu/realtime/webcam/kcam_1.jpg
    robotic: false
    group_names:
      - Program A
    token: "load_demo_data token"
  - name: Keck I Telescope
    nickname: Keck1
    lat: 19.8283
    lon: -155.478
    elevation: 2000
    diameter: 2.56
    skycam: https://www2.keck.hawaii.edu/realtime/webcam/kcam_1.jpg
    robotic: false
    group_names:
      - Program A
    token: "load_demo_data token"
instruments:
  - name: P60 Camera
    type: imager
    band: optical
    telescope_nickname: P60
    filters: ["ztfg", "ztfr", "ztfi"]
    token: "load_demo_data token"
  - name: ALFOSC
    type: imaging spectrograph
    band: optical
    telescope_nickname: NOT
    token: "load_demo_data token"
  - name: ESI
    type: spectrograph
    band: optical
    telescope_nickname: Keck2
    token: "load_demo_data token"
  - name: LRIS
    type: spectrograph
    band: optical
    telescope_nickname: Keck1
    token: "load_demo_data token"
observing_runs:
  - pi: Danny Goldstein
    instrument_name: ESI
    calendar_date: 2021-02-16
    group: Program A
    token: "load_demo_data token"
    observers: "Danny Goldstein, Peter Nugent"
    key: "esi_run"
  - pi: Danny Goldstein
    instrument_name: LRIS
    calendar_date: 2021-06-17
    group: Program A
    token: "load_demo_data token"
    observers: "Danny Goldstein, Peter Nugent"
    key: "lris_run"
sources:
  - id: 14gqr
    candidate:
      candidate_filters:
        - "example filter"
    unsaved_candidate_copy:
      candidate_id: 14gqr_unsaved_copy
      candidate_filters:
        - "example filter"
      comments:
        - "No source at transient location to R>26 in LRIS imaging"
        - "Strong calcium lines have emerged."
    photometry:
      data: "skyportal/tests/data/phot.csv"
      instrument_name: P60 Camera
    spectroscopy:
      data: "skyportal/tests/data/spec.csv"
      instrument_name: ALFOSC
      observed_at: "2019-10-24T00:00:00"
    ra: 353.36647
    dec: 33.646149
    redshift: 0.063
    altdata:
      simbad:
        class: RRLyr
    group_names:
      - Program A
    comments:
      - "No source at transient location to R>26 in LRIS imaging"
      - "Strong calcium lines have emerged."
    thumbnails:
      new: skyportal/tests/data/14gqr_new.png
      ref: skyportal/tests/data/14gqr_ref.png
      sub: skyportal/tests/data/14gqr_sub.png
    token: "load_demo_data token"
  - id: 16fil
    candidate:
      candidate_filters:
        - "example filter"
    unsaved_candidate_copy:
      candidate_id: 16fil_unsaved_copy
      candidate_filters:
        - "example filter"
      comments:
        - "Dogs in the park"
        - "Birds are not real"
    photometry:
      data: "skyportal/tests/data/phot.csv"
      instrument_name: P60 Camera
    spectroscopy:
      data: "skyportal/tests/data/spec.csv"
      instrument_name: ALFOSC
      observed_at: "2019-10-24T00:00:00"
    ra: 322.718872
    dec: 27.574113
    redshift: 0.0
    altdata:
      simbad:
        class: RRLyr
    group_names:
      - Program A
    comments:
      - "Frogs in the pond"
      - "The eagle has landed"
    thumbnails:
      new: skyportal/tests/data/16fil_new.png
      ref: skyportal/tests/data/16fil_ref.png
      sub: skyportal/tests/data/16fil_sub.png
    token: "load_demo_data token"
taxonomies:
  - name: Demo taxonomy
    tdtax: true
    version: latest
    provenance: https://github.com/profjsb/timedomain-taxonomy
    token: "load_demo_data token"
    groups:
      - Program A
      - Program B
assignments:
  - source_id: 14gqr
    run_key: lris_run
    priority: 4
    comment: Please get 2x625s
    token: "load_demo_data token"
  - source_id: 16fil
    run_key: lris_run
    priority: 3
    comment: Please do i-band imaging to 24th mag
    token: "load_demo_data token"
  - source_id: 14gqr
    run_key: esi_run
    priority: 2
    comment: Please integrate for 1200s
    token: "load_demo_data token"
  - source_id: 16fil
    run_key: esi_run
    priority: 2
    comment: Please take only when seeing is less than 1.5"
    token: "load_demo_data token"
