name: Test SkyPortal

on: [push, pull_request]

jobs:
  test:
    name: Test SkyPortal
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: anything
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a
        # healthcheck
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Lint
        run: |
          pip install pre-commit
          if pre-commit run --from-ref origin/master --to-ref HEAD; then
              echo "Linting errored; this will be fatal sometime in the near future"
          fi

      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.cache/sphinx
            ~/.ccache
            ~/.local
            ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Write SkyPortal config
        run: |
            cat << EOF > config.yaml
              database:
                database: skyportal
                host: localhost
                port: 5432
                user: skyportal
                password: anything
            EOF

      - name: Install system dependencies
        run: |
          sudo apt-add-repository -y ppa:nginx/stable
          sudo apt install -y ccache wget nodejs unzip firefox nginx

          export PATH=/usr/lib/ccache:${PATH}
          ccache -s

          pip install --upgrade pip
          pip install wheel numpy

          export NPM_PACKAGES="${HOME}/.npm-packages"
          export PATH=${NPM_PACKAGES}/bin:$PATH
          export NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"

          sudo npm -g install npm@next

          which python; python --version
          echo npm $(npm --version)
          echo node $(node --version)
          nginx -v
          firefox --version

      - name: Install SkyPortal dependencies
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          make dependencies

      - name: Initialize SkyPortal
        run: |
          make db_init
          pip list --format=columns
          npm ls --depth 0

      - name: Build docs
        run: |
            pip install -r requirements.docs.txt
            make docs

      - name: Install Geckodriver / Selenium
        run: |
          GECKO_VER=0.27.0
          CACHED_DOWNLOAD_DIR=~/.local/downloads

          wget https://github.com/mozilla/geckodriver/releases/download/v${GECKO_VER}/geckodriver-v${GECKO_VER}-linux64.tar.gz --directory-prefix=${CACHED_DOWNLOAD_DIR} --no-clobber
          sudo tar -xzf ${CACHED_DOWNLOAD_DIR}/geckodriver-v${GECKO_VER}-linux64.tar.gz -C /usr/local/bin
          geckodriver --version
          pip install --upgrade selenium
          python -c "import selenium; print(f'Selenium {selenium.__version__}')"

      - name: Test loading demo data
        run: |
          make run &
          sleep 5 && make load_demo_data
          kill %1

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1.2
        with:
          run: |
            make log &
            make test

      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: log
