name: Test Skyportal Docker Build

on:
  push:
    branches:
      - master
      - test-docker

jobs:
  test:
    name: Test SkyPortal Docker build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache
            ~/.local
            ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Install Docker and Docker Compose
        run: |
          docker --version
          docker-compose --version

      - name: Build Docker image
        run: |
          make docker-local

      - name: Start containers
        run: |
          docker-compose up -d

      - name: Create database tables
        run: |
          # Give plenty of time for containers to fully spin up
          sleep 90
          docker exec skyportal_web_1 bash -c 'source /skyportal_env/bin/activate && PYTHONPATH=$PYTHONPATH:"." python skyportal/initial_setup.py --config=config.yaml --username testuser@cesium-ml.org'

      - name: Test loading demo data
        run: |
          docker exec skyportal_web_1 bash -c 'source /skyportal_env/bin/activate && make load_demo_data'
